# Generated by Django 5.0.7 on 2024-08-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="imageUrl",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="redirectUrl",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
