# Generated by Django 5.0.7 on 2024-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_agent_imageurl_agent_redirecturl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="redirectUrl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
